import type { Metadata } from 'next';
import { Poppins, Vazirmatn } from 'next/font/google';
import './globals.css';

import MainHeader from '@/components/MainHeader';
import { ThemeProvider } from '@/components/ThemeProvider';

const poppins = Poppins({
  weight: [
    '100',
    '200',
    '300',
    '400',
    '500',
    '600',
    '700',
    '800',
    '900',
  ],
  subsets: ['latin', 'latin-ext'],
});

const vazir = Vazirmatn({
  variable: '--font-vazir',
  subsets: ['arabic', 'latin', 'latin-ext'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${vazir.variable} ${poppins.className} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <MainHeader />
          <main className="max-w-4xl mx-auto">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
